init_from: 'scratch'
device: 'cpu'
dtype: 'float16'
batch_size: 32

num_epochs: 10
dim: 256
n_layers: 2
n_heads: 4
n_kv_heads: 4
vocab_size: 64793
max_seq_len: 256
hidden_dim: 512
dropout: 0.0

lr: 0.0003
beta1: 0.9
beta2: 0.98
