out_dir: '../00_assets/'
num_epochs: 10
init_from: 'scratch'
batch_size: 32
vocab_size: 64793
max_seq_len: 256
dim: 256
n_layers: 2
n_heads: 4
multiple_of: 8
dropout: 0.0
lr: 0.0003  # max learning rate
beta1: 0.9
beta2: 0.98
device: 'cpu'
dtype: 'float16'