model_version: v1
geo_code_type: geohash
model_name: roberta-base
num_epochs: 10
batch_size: 128
num_encode: 3
num_decode: 3
d_model: 512
n_head: 8
lr: 0.0001
betas: (0.9, 0.98)
eps: 1e-9
device: cpu
